### PR TITLE
Hotfix for building SmL2P under linux

### PR DESCRIPTION
**Pull request by justin-time**
Add a config line to use c++11 under linux.

### CODE REVIEW

**Comment by ekiwi** [comment]
I can confirm, that this patch makes it possible to build the latest master branch of `Sync-my-L2P` on Fedora.

**Comment by justin-time** [comment]
This PR is not merged before releasing 2.2.0?! SmL2P is broken for linux without this fix.

**Comment by ekiwi** [comment]
At least the .pro file on the master branch does not contain the C++11 CONFIG, which is why I needed your patch.

**Comment by Sync-my-L2P** [comment]
Sorry, my mistake.

**Comment by justin-time** [comment]
No problem, I have included this patch into the 2.2.0 linux packages on my own :-)

**Pull request merged**
